### ISSUE TITLE
readxl output in Rmarkdown

### ISSUE THREAD

**Issue by mroutley** [mroutley/analytics_with_r#1]
As described in hadley/readxl#82 when reading certain xls files DEFINEDNAME errors are rendered to the console. These errors appear in Markdown output as well. To avoid this, I import an xlsx file in the RMarkdown demonstration.

**Comment by ghost** [comment]
I'm not sure if you're still having issues with this, but I just came across this issue when Googling a similar problem and thought I'd comment for anyone who finds it in the future. I found that the easiest way to handle it was to just utilize two different code chunks:

`````` r
# ``` {r, results = "hide", message = FALSE}
# library(readxl)
# dat <- read_excel("path/to/my.xls")
# ```
# ``` {r}
# head(dat)
# ```
``````

In the markdown document, the code is now run without the output of the DEFINEDNAME. I agree that having a way to suppress this in the options menu to avoid double code chunks would be nice, but it might be one of those situations where the effort to rework the source code is more effort than a simple work around.

**Comment by mroutley** [comment]
Thanks @bbritten ! Somehow only just saw this now. Looks like readxl v1.0 fixes this issue. So, just waited long enough and someone else fixed it.
